<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="coverlet.collector" Version="10.0.1" />
        <PackageVersion Include="coverlet.msbuild" Version="10.0.1" />
        <PackageVersion Include="FluentValidation" Version="12.1.1" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
        <PackageVersion Include="MongoDB.Bson" Version="3.10.0" />
        <PackageVersion Include="MongoDB.Driver" Version="3.10.0" />
        <PackageVersion Include="Moq" Version="4.20.72" />
        <PackageVersion Include="Newtonsoft.Json.Schema" Version="4.0.1" />
        <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
        <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
        <PackageVersion Include="xunit" Version="2.9.3" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    </ItemGroup>

</Project>
