<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>IntegrationTest.Infra.MongoDB</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <SonarQubeSetting Include="sonar.coverage.exclusions">
            <Value>mongo-init.js</Value>
        </SonarQubeSetting>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.msbuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\main\Infra.MongoDB\Infra.MongoDB.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="local.settings.json"/>
        <Content Include="test.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </Content>
        <None Remove="StrykerOutput\**"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="StrykerOutput\**"/>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Remove="StrykerOutput\**"/>
    </ItemGroup>
    <ItemGroup>
        <None Remove="StrykerOutput\**"/>
    </ItemGroup>

</Project>