//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryPoint.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntryPoint.WebApi.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request received is invalid. Check the format and the parameters in the documentation, correct them and try again..
        /// </summary>
        internal static string CommonInvalidRequest {
            get {
                return ResourceManager.GetString("CommonInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string CommonJsonPropertyInvalid {
            get {
                return ResourceManager.GetString("CommonJsonPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is required..
        /// </summary>
        internal static string CommonJsonPropertyMissing {
            get {
                return ResourceManager.GetString("CommonJsonPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; has a value not compatible with it&apos;s expected type..
        /// </summary>
        internal static string CommonJsonPropertyWrongType {
            get {
                return ResourceManager.GetString("CommonJsonPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again later!.
        /// </summary>
        internal static string CommonUnexpectedException {
            get {
                return ResourceManager.GetString("CommonUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again later! Details: {0}..
        /// </summary>
        internal static string CommonUnexpectedExceptionWithParams {
            get {
                return ResourceManager.GetString("CommonUnexpectedExceptionWithParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and send your information again!.
        /// </summary>
        internal static string CommonValidationAlert {
            get {
                return ResourceManager.GetString("CommonValidationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial &apos;Created at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyFromCreatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyFromCreatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial &apos;Updated at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyFromUpdatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyFromUpdatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final &apos;Created at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyToCreatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyToCreatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final &apos;Updated at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyToUpdatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyToUpdatedAtIsInvalid", resourceCulture);
            }
        }
    }
}
