//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace EntryPoint.WebApi.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Messages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("EntryPoint.WebApi.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request received is invalid. Check the format and the parameters in the documentation, correct them and try again..
        /// </summary>
        internal static string CommonInvalidRequest {
            get {
                return ResourceManager.GetString("CommonInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string CommonJsonPropertyInvalid {
            get {
                return ResourceManager.GetString("CommonJsonPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is required..
        /// </summary>
        internal static string CommonJsonPropertyMissing {
            get {
                return ResourceManager.GetString("CommonJsonPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; has a value not compatible with it&apos;s expected type..
        /// </summary>
        internal static string CommonJsonPropertyWrongType {
            get {
                return ResourceManager.GetString("CommonJsonPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again later!.
        /// </summary>
        internal static string CommonUnexpectedException {
            get {
                return ResourceManager.GetString("CommonUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again later! Details: {0}..
        /// </summary>
        internal static string CommonUnexpectedExceptionWithParams {
            get {
                return ResourceManager.GetString("CommonUnexpectedExceptionWithParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and send your information again!.
        /// </summary>
        internal static string CommonValidationAlert {
            get {
                return ResourceManager.GetString("CommonValidationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial &apos;created at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyFromCreatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyFromCreatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial &apos;updated at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyFromUpdatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyFromUpdatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property id is required..
        /// </summary>
        internal static string ValidationPropertyIdIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationPropertyIdIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No property was found with identifier {0}..
        /// </summary>
        internal static string ValidationPropertyNotFound {
            get {
                return ResourceManager.GetString("ValidationPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final &apos;created at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyToCreatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyToCreatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final &apos;updated at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyToUpdatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyToUpdatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The advertise &apos;transaction&apos; field is required..
        /// </summary>
        internal static string ValidationPropertyTransactionIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationPropertyTransactionIsNullOrEmpty", resourceCulture);
            }
        }
    }
}
