//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryPoint.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntryPoint.WebApi.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request received is invalid. Check the format and the parameters in the documentation, correct them and try again..
        /// </summary>
        internal static string CommonInvalidRequest {
            get {
                return ResourceManager.GetString("CommonInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string CommonJsonPropertyInvalid {
            get {
                return ResourceManager.GetString("CommonJsonPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is required..
        /// </summary>
        internal static string CommonJsonPropertyMissing {
            get {
                return ResourceManager.GetString("CommonJsonPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; has a value not compatible with it&apos;s expected types..
        /// </summary>
        internal static string CommonJsonPropertyWrongType {
            get {
                return ResourceManager.GetString("CommonJsonPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again later!.
        /// </summary>
        internal static string CommonUnexpectedException {
            get {
                return ResourceManager.GetString("CommonUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again later! Details: {0}..
        /// </summary>
        internal static string CommonUnexpectedExceptionWithParams {
            get {
                return ResourceManager.GetString("CommonUnexpectedExceptionWithParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and send your information again!.
        /// </summary>
        internal static string CommonValidationAlert {
            get {
                return ResourceManager.GetString("CommonValidationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial area cannot exceed the maximum allowed area..
        /// </summary>
        internal static string ValidationPropertyAreaIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyAreaIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial built area cannot exceed the maximum allowed built area..
        /// </summary>
        internal static string ValidationPropertyBuiltAreaIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyBuiltAreaIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial &apos;created at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyFromCreatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyFromCreatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial &apos;updated at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyFromUpdatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyFromUpdatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property id is required..
        /// </summary>
        internal static string ValidationPropertyIdIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationPropertyIdIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No property was found with identifier {0}..
        /// </summary>
        internal static string ValidationPropertyNotFound {
            get {
                return ResourceManager.GetString("ValidationPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial number of bedrooms cannot be greater than the maximum number of bedrooms..
        /// </summary>
        internal static string ValidationPropertyNumberOfBedroomsIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyNumberOfBedroomsIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial number of garages cannot be greater than the maximum number of garages..
        /// </summary>
        internal static string ValidationPropertyNumberOfGaragesIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyNumberOfGaragesIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial number of toilets cannot be greater than the maximum number of toilets..
        /// </summary>
        internal static string ValidationPropertyNumberOfToiletsIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyNumberOfToiletsIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial price per m2 cannot be greater than the maximum price per m2..
        /// </summary>
        internal static string ValidationPropertyPriceByM2IsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyPriceByM2IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;ranking&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyRankingIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyRankingIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial rental price cannot be greater than the maximum rental price..
        /// </summary>
        internal static string ValidationPropertyRentalPriceIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyRentalPriceIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial rental total price cannot be greater than the maximum rental total price..
        /// </summary>
        internal static string ValidationPropertyRentalTotalPriceIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyRentalTotalPriceIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial selling price cannot be greater than the maximum selling price..
        /// </summary>
        internal static string ValidationPropertySellingPriceIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertySellingPriceIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;status&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyStatusIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyStatusIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final &apos;created at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyToCreatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyToCreatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final &apos;updated at&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyToUpdatedAtIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyToUpdatedAtIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;transaction&apos; field is invalid..
        /// </summary>
        internal static string ValidationPropertyTransactionIsInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyTransactionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The advertise &apos;transaction&apos; field is required..
        /// </summary>
        internal static string ValidationPropertyTransactionIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationPropertyTransactionIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;types&apos; field is required..
        /// </summary>
        internal static string ValidationPropertyTypesAreInvalid {
            get {
                return ResourceManager.GetString("ValidationPropertyTypesAreInvalid", resourceCulture);
            }
        }
    }
}
