name: LikeC4 Site Generation

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/likec4-site-generation.yml"
      - "docs/likec4/*"
  workflow_call:    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: 📰 Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: 📦 Setup NodeJs [v22]
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 22   

      - name: 🛠️ Install dependencies
        working-directory: ./docs/likec4
        run: |
          npm ci --ignore-scripts
          npx --no -- likec4 --version

      - name: ⚙️ Build LikeC4
        working-directory: ./docs/likec4
        run: |
          npx --no -- likec4 build -o ./dist --base properties-api-netcore

      - name: 📡 Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: ./docs/likec4/dist
          
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4

      - name: 📱 Success
        run: |
          echo "🎉 C4 Diagrams deployed to GitHub Pages"
